Fix "localtime_r" undefined build error
This change bypass the following build error after updating to 1.02p:

    /proc/self/cwd/vendor/intel/external/openssl/crypto/mem_dbg.c:648:
    undefined reference to `localtime_r'

Change-Id: I5c1ea90503d621228cb78095cb99019cb7c7baca
Tracked-On: OAM-67987
Signed-off-by: Yang, Kai <kaix.yang@intel.com>
Reviewed-on: 644036